[package]
name = "signs"
version = "0.1.0"
edition = "2024"
description = "A tool for creating signs."
keywords = ["mutcd", "fhwa", "traffic-signs", "road-signs"]
readme = "README.md"
homepage = "https://github.com/scarcekoi/signs"
repository = "https://github.com/scarcekoi/signs"
license = "MIT"

[dependencies]
mutcd-colors = "0.1.1"
